### ISSUE TITLE
<typeout> in hero not working

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode-summit#91]
Expected:
http://gdg-x.github.io/zeppelin/
like shown above typeoutTextValues from _config.yml '"", "Dev", "Users", "World"' should be typed.

Actual:
The typeout function does not work and uses the static fallback value ""

**Comment by t-book** [comment]
@gannebamm it's the document ready function or something else in it. Put the function call separately before the closing html tag and it should work:

```
    <script>
      $( document ).ready(function() {
        if ($(window).width() > 767) {
            $("#typeout-text").typed({
                strings: ["", "Dev", "Users", "World"],
                typeSpeed: 150,
                backDelay: 900,
                loop: true
            });
        }
      });
    </script>
</body>
```

Unfortuantely I do not have time to inspect the current code. But it should at least help to get it typing ;)

**Comment by t-book** [comment]
(forgot) position: https://github.com/GeoNode/geonode-summit/blob/574452033bc5857ce940e88e9b2cee5d94929fec/_layouts/default.html#L80-L85 
Further make sure that typed js. is loaded. (otherwise include it via cdn)

`    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>`
